// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  listActive: require('../Images/Icons/list-selected.png'),
  listInActive: require('../Images/Icons/list-unselected.png'),
  imageListActive: require('../Images/Icons/image-list-selected.png'),
  imageListInActive: require('../Images/Icons/image-list-unselected.png'),
  helpActive: require('../Images/Icons/help-selected.png'),
  helpInActive: require('../Images/Icons/help-unselected.png'),
  readActive: require('../Images/Icons/read-selected.png'),
  readInActive: require('../Images/Icons/read-unselected.png'),
  readDetailsActive: require('../Images/Icons/read-detail-selected.png'),
  readDetailsInActive: require('../Images/Icons/read-detail-unselected.png'),
  audioActive: require('../Images/Icons/speaker.png'),
  audioInActive: require('../Images/Icons/speaker-mute-grey.png'),
  favoriteActive: require('../Images/Icons/heart-selected.png'),
  favoriteInActive: require('../Images/Icons/heart-unselected.png'),
  defaultAvatar: require('../Images/Icons/defaultAvatar.jpg'),
  tagIcon: require('../Images/Icons/tag-icon.png')
}

export default images
